### ISSUE TITLE
Add Php Cli and pcntl

### ISSUE THREAD

**Issue by GaetanPTX** [NightMeer/ApachePHP8-Docker#1]
Hello, can you add support for php cli and pcntl. THANKS !

I use the version of apachephp8-docker on unraid

**Comment by NightMeer** [comment]
Hey, 

I have added pcntl. php-cli should be able to use.

**Comment by NightMeer** [comment]
Hey, 

I have added pcntl.
PHP-CLI should be able to use. If it isnt please Contact me :)
